#整合Mybatis
mybatis:
  config-location: classpath:SqlMapConfig.xml
  mapper-locations: classpath:com/itgaoshu/mapper/*Mapper.xml
  type-aliases-package: com.itgaoshu.bean
#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:

#整合redis
  redis:
    host:
    port:
